{{- if .Values.elasticsearch.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-stack.labels" . | nindent 4 }}
spec:
  version: {{ .Values.elasticsearch.version }}
  volumeClaimDeletePolicy: {{ .Values.elasticsearch.volumeClaimDeletePolicy }}
  nodeSets:
    # Master nodes
    - name: masters
      count: {{ .Values.elasticsearch.nodeSets.masters.count }}
      config:
        node.roles: {{ .Values.elasticsearch.nodeSets.masters.roles | toJson }}
      podTemplate:
        spec:
          {{- if .Values.elasticsearch.nodeSets.masters.podTemplate.spec.affinity }}
          affinity:
            {{- toYaml .Values.elasticsearch.nodeSets.masters.podTemplate.spec.affinity | nindent 12 }}
          {{- end }}
          {{- if .Values.elasticsearch.common.initContainers.sysctl.enabled }}
          initContainers:
          - name: sysctl
            image: {{ default (printf "docker.elastic.co/elasticsearch/elasticsearch:%s" .Values.elasticsearch.version) .Values.elasticsearch.common.initContainers.sysctl.image }}
            command: {{ .Values.elasticsearch.common.initContainers.sysctl.command | toJson }}
            securityContext: {{ .Values.elasticsearch.common.initContainers.sysctl.securityContext | toJson }}
          {{- end }}
          containers:
          - name: elasticsearch
            resources:
              {{- toYaml .Values.elasticsearch.nodeSets.masters.resources | nindent 14 }}
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - {{ .Values.elasticsearch.common.storage.accessMode }}
          resources:
            requests:
              storage: {{ .Values.elasticsearch.nodeSets.masters.storage.size }}
          storageClassName: {{ .Values.elasticsearch.common.storage.storageClassName }}

    # Data nodes
    - name: data
      count: {{ .Values.elasticsearch.nodeSets.data.count }}
      config:
        node.roles: {{ .Values.elasticsearch.nodeSets.data.roles | toJson }}
      podTemplate:
        spec:
          {{- if .Values.elasticsearch.nodeSets.data.podTemplate.spec.affinity }}
          affinity:
            {{- toYaml .Values.elasticsearch.nodeSets.data.podTemplate.spec.affinity | nindent 12 }}
          {{- end }}
          containers:
          - name: elasticsearch
            resources:
              {{- toYaml .Values.elasticsearch.nodeSets.data.resources | nindent 14 }}
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - {{ .Values.elasticsearch.common.storage.accessMode }}
          resources:
            requests:
              storage: {{ .Values.elasticsearch.nodeSets.data.storage.size }}
          storageClassName: {{ .Values.elasticsearch.common.storage.storageClassName }}

    # Ingest nodes
    - name: ingest
      count: {{ .Values.elasticsearch.nodeSets.ingest.count }}
      config:
        node.roles: {{ .Values.elasticsearch.nodeSets.ingest.roles | toJson }}
      podTemplate:
        spec:
          {{- if .Values.elasticsearch.nodeSets.ingest.podTemplate.spec.affinity }}
          affinity:
            {{- toYaml .Values.elasticsearch.nodeSets.ingest.podTemplate.spec.affinity | nindent 12 }}
          {{- end }}
          containers:
          - name: elasticsearch
            resources:
              {{- toYaml .Values.elasticsearch.nodeSets.ingest.resources | nindent 14 }}
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - {{ .Values.elasticsearch.common.storage.accessMode }}
          resources:
            requests:
              storage: {{ .Values.elasticsearch.nodeSets.ingest.storage.size }}
          storageClassName: {{ .Values.elasticsearch.common.storage.storageClassName }}

    {{- if .Values.elasticsearch.nodeSets.coordinating }}
    # Coordinating nodes
    - name: coordinating
      count: {{ .Values.elasticsearch.nodeSets.coordinating.count }}
      config:
        node.roles: {{ .Values.elasticsearch.nodeSets.coordinating.roles | toJson }}
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              {{- toYaml .Values.elasticsearch.nodeSets.coordinating.resources | nindent 14 }}
    {{- end }}

  http:
    tls:
      selfSignedCertificate:
        disabled: false
    service:
      spec:
        type: {{ .Values.elasticsearch.http.service.spec.type }}

  transport:
    service:
      spec:
        type: {{ .Values.elasticsearch.http.service.spec.type }}
{{- end }}
