{{- if .Values.kibana.enabled }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-stack.labels" . | nindent 4 }}
spec:
  version: {{ .Values.kibana.version }}
  count: {{ .Values.kibana.count }}
  auth:
    {{- with .Values.kibana.auth }}
    username: {{ .username }}
    password: {{ .password }}
    {{- end }}
  security:
    {{- with .Values.kibana.security }}
    tls:
      enabled: {{ .tls.enabled }}
    {{- end }}
  auth:
    fileRealm:
    - secretName: kibana-credentials
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          {{- toYaml .Values.kibana.resources | nindent 10 }}
  http:
    service:
      spec:
        type: {{ .Values.kibana.service.type }}
{{- end }}
