apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-metrics
  namespace: elastic-system
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch-cluster
spec:
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch-cluster
