{{- if .Values.elasticsearch.ilm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.elasticsearch.name }}-ilm-policies
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-operator.labels" . | nindent 4 }}
data:
  hot-warm-cold-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_age": "1d",
                "max_primary_shard_size": "50gb"
              },
              "set_priority": {
                "priority": 100
              }
            }
          },
          "warm": {
            "min_age": "{{ .Values.elasticsearch.ilm.policies.policy.warm.maxAge }}",
            "actions": {
              "allocate": {
                "require": {
                  "data": "warm"
                }
              },
              "forcemerge": {
                "max_num_segments": 1
              }
            }
          },
          "cold": {
            "min_age": "{{ .Values.elasticsearch.ilm.policies.policy.cold.maxAge }}",
            "actions": {
              "allocate": {
                "require": {
                  "data": "cold"
                }
              }
            }
          },
          "delete": {
            "min_age": "{{ .Values.elasticsearch.ilm.policies.policy.delete.minAge }}",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
{{- end }}
