apiVersion: v2
name: elastic-operator
description: A Helm chart for deploying Elastic Stack with ECK operator on Kubernetes
type: application
version: 0.1.0
appVersion: 3.1.0
dependencies:
  - name: eck-operator-crds
    version: 3.1.0
    repository: "https://helm.elastic.co"
    condition: installCRDs
  - name: eck-operator
    version: 3.1.0
    repository: "https://helm.elastic.co"
    condition: operator.enabled