# Main configuration for the elastic-operator chart

# Install CRDs
installCRDs: false  # Skip CRD installation as they are already installed

# Operator configuration
operator:
  enabled: true
  managedNamespaces: ["elastic-system"]  # Specific namespace
  createClusterScopedResources: true
  config:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      runAsUser: 1000
    logVerbosity: "0"
    metricsPort: 8080
    metrics:
      container:
        port: 8080
      service:
        enabled: true
        type: ClusterIP
      serviceMonitor:
        enabled: true
        namespace: monitoring
        interval: 30s
        scrapeTimeout: 10s
        labels:
          release: prometheus
  webhook:
    enabled: true
    manageCerts: true
    certValidityDuration: 8760h
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "250Mi"
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: elastic-operator
